### ISSUE TITLE
局部注册的时候，导入文件为空

### ISSUE THREAD

**Issue by chenwen97** [Lruihao/el-table-sticky#16]
```
import {
  StickyHeader,
  StickyFooter,
  StickyScroller,
  HeightAdaptive,
} from '@cell-x/el-table-sticky'
```

局部导入时，这个4个对象都为空，导致directives注册失败，不知道什么原因。

相关版本
nodejs: 16.20.2
npm: 8.19.4
"@cell-x/el-table-sticky": "^1.0.2",
"element-ui": "2.4.11",
"vue": "^2.5.2",

**Comment by Lruihao** [comment]
我明天看看

**Comment by Lruihao** [comment]
1.0.3 版本已修复
<img width="639" alt="image" src="https://github.com/Lruihao/el-table-sticky/assets/33419593/6f6fbedc-fce6-41fc-b3c4-565529765c93">
