### ISSUE TITLE
通过bind传入指令时，未生效

### ISSUE THREAD

**Issue by git-shiwu** [Lruihao/el-table-sticky#18]
![image](https://github.com/Lruihao/el-table-sticky/assets/39177154/ec904674-5f2e-42ab-87de-575c64907055)
如图所示，把v-sticky-header.always指令作为Attribute传入时，指令并未生效，请问有没有好的解决方案?

**Comment by Lruihao** [comment]
@git-shiwu 是不是没有正常引入 el-table-sticky

**Comment by git-shiwu** [comment]
我大概知道怎么回事了，我们项目组件封装的问题，跟您这边没关系🤦
